### ISSUE TITLE
Changed title

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#10]
Test issue to see what happens if use its number in other merge comment

**Comment by commiteth** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0xf1ec1e7bacce8215f0b46e5e593562e30b65bedb](https://ropsten.etherscan.io/address/0xf1ec1e7bacce8215f0b46e5e593562e30b65bedb)
Network: Testnet (Ropsten)
Paid to: annadanchenko
