### ISSUE TITLE
Price in Top Hunters if got only STT (по-русски)

### ISSUE THREAD

**Issue by annadanchenko** [anna01test/c1#15]
check price

**Comment by commiteth** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x7c6937edf4795d971e09128ffcdd9eaeeec18c86](https://ropsten.etherscan.io/address/0x7c6937edf4795d971e09128ffcdd9eaeeec18c86)
Network: Testnet (Ropsten)
Paid to: annadanchenko
