### ISSUE TITLE
Demo case

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#17]
make a demo

**Comment by commiteth** [comment]
Current balance: 0.0 ETH
Contract address: [0xe9eb037a80da70c5465e185ca6f5588d1dc73a23](https://ropsten.etherscan.io/address/0xe9eb037a80da70c5465e185ca6f5588d1dc73a23)
![QR Code](https://commiteth.com:444/qr/anna01test/c1/bounty/17/83ed00d737e04a6428566f38b43de5c811832ebca8f3d480a1e50d03c15f6653/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://commiteth.com:444](https://commiteth.com:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.

**Comment by anna01test** [comment]
closed
