### ISSUE TITLE
Open test

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#18]
fix  me

**Comment by commiteth** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0xd7b22ca21fd8bacd2776bce0c2eb4311ddf07fd3](https://ropsten.etherscan.io/address/0xd7b22ca21fd8bacd2776bce0c2eb4311ddf07fd3)
Network: Testnet (Ropsten)
Paid to: annadanchenko
