### ISSUE TITLE
-------------------------- New bot test

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#19]
hello

**Comment by commiteth** [comment]
Current balance: 0.054 ETH
Contract address: [0x57b440e5e243353341636dd3f29e571f1fefa1c5](https://ropsten.etherscan.io/address/0x57b440e5e243353341636dd3f29e571f1fefa1c5)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/19/2d4a943bfdb837b9f0abb156921cb68dc35f2d6988f4cb5f670714f6c6f58caf/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
