### ISSUE TITLE
Second issue to fix

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#22]
two

**Comment by commiteth** [comment]
Current balance: 0.2 ETH
Tokens: SNT: 21.00
Contract address: [0x26332f5633a640821e42c5695dc1870df82d1708](https://ropsten.etherscan.io/address/0x26332f5633a640821e42c5695dc1870df82d1708)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/22/d22decdb1926a514fbb5efcc4f0163d6153f8c5721ac77a1df11c6af5cfc13d6/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
