### ISSUE TITLE
Issue is added by another contributor

### ISSUE THREAD

**Issue by anna02test** [anna01test/c1#25]
found this error

**Comment by commiteth** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x123328987c5dc95bcac9f2d5eee29dd05a03f11fc19f0160748326cce1730354](https://ropsten.etherscan.io/tx/0x123328987c5dc95bcac9f2d5eee29dd05a03f11fc19f0160748326cce1730354)

**Comment by anna01test** [comment]
yes would be good to fix it
