### ISSUE TITLE
Add comment after PR is subbmited

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#27]
see title

**Comment by commiteth** [comment]
Balance: 0.0000 ETH
Contract address: [0x4f9d74f50bc4b64e343ae49202a923ab0eec15b5](https://ropsten.etherscan.io/address/0x4f9d74f50bc4b64e343ae49202a923ab0eec15b5)
Network: Testnet (Ropsten)
Status: pending maintainer confirmation
Winner: annadanchenko
