### ISSUE TITLE
ttest

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#29]

**Comment by commiteth** [comment]
Current balance: 0.0 ETH
Contract address: [0x6d3351a5f114f2c5f94bc42bde3740141d2b7710](https://ropsten.etherscan.io/address/0x6d3351a5f114f2c5f94bc42bde3740141d2b7710)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/29/6a6f93e60cecc11f625a055a4d91d42e989e83b68e14286bbb4ce5472b414258/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
