### ISSUE TITLE
Bot title

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#30]
123

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x8624950151f6c5dccd0d557d78a91a1ab7cac028](https://ropsten.etherscan.io/address/0x8624950151f6c5dccd0d557d78a91a1ab7cac028)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/30/899d20998707b5e0484fb24eca4533f54a06ad56df7bf551ba2aa84cf7e25354/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
