### ISSUE TITLE
Another title

### ISSUE THREAD

**Issue by annadanchenko** [anna01test/c1#31]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x03176fec3ede17dcf18ed02b0fe4bd0eb7382944](https://ropsten.etherscan.io/address/0x03176fec3ede17dcf18ed02b0fe4bd0eb7382944)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/31/2d930da15ab01b91109abd2aa6da2c5fe08c58a9a289c77ee7a6b0cd5f359967/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
