### ISSUE TITLE
Remove bounty but do not close isse

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#32]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x76a9d9e6c715ada0e6c91f5912c1c0142a4f9c2a](https://ropsten.etherscan.io/address/0x76a9d9e6c715ada0e6c91f5912c1c0142a4f9c2a)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/32/f4fc745e6323507e7d0117b069dbb9d35067e2a9083f32470d125b56c307a48a/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
