### ISSUE TITLE
Close issue with bounty - see it's not in the Bounties list

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#33]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x5515409492d8f6469cc32f55ae928e7d1674d14a](https://ropsten.etherscan.io/address/0x5515409492d8f6469cc32f55ae928e7d1674d14a)
![QR Code](https://openbounty.status.im:444/qr/anna01test/c1/bounty/33/06595e00148e9fecc3ff54a2cb3f41b2d1998f9d4a77e569920a3a985e67d835/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
