### ISSUE TITLE
Write more text

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#5]
add more test to test fiel

**Comment by commiteth** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x9d8f443d1f039d9ec0200f9e53861f4da8006c3c](https://ropsten.etherscan.io/address/0x9d8f443d1f039d9ec0200f9e53861f4da8006c3c)
Network: Testnet (Ropsten)
Paid to: annadanchenko
