### ISSUE TITLE
Check STT

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#6]
Get Stt for merge

**Comment by commiteth** [comment]
Current balance: 0.023457 ETH
Tokens: SNT: 25.12
Contract address: [0x647e25066b9954bacd60c68162c36f7d540ef166](https://ropsten.etherscan.io/address/0x647e25066b9954bacd60c68162c36f7d540ef166)
![QR Code](https://commiteth.com:444/qr/anna01test/c1/bounty/6/1fa9f4820f06a1d3b1b853cdfa9404c490ebb784a6c753b4b8f53de4505f005f/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://commiteth.com:444](https://commiteth.com:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
