### ISSUE TITLE
Write wrong number in the merge message

### ISSUE THREAD

**Issue by anna01test** [anna01test/c1#9]
see what happens if resolves #NN is in comment

**Comment by commiteth** [comment]
Balance: 0.0100 ETH
Tokens: SNT: 0.00
Contract address: [0x61da1b575633c7fbc59f3fe94ccdc646621584d6](https://ropsten.etherscan.io/address/0x61da1b575633c7fbc59f3fe94ccdc646621584d6)
Network: Testnet (Ropsten)
Paid to: annadanchenko
